### ISSUE TITLE
The backend provides information about every players's score to the frontend

### ISSUE THREAD

**Issue by Elyisha** [sopra-fs24-group-38/sopra-fs24-group-38-server#101]

**Comment by Elyisha** [comment]
da4c2e0201026837af9e35cb6373606e207617c8

**Comment by samuelfrnk** [comment]
51114b9b7c5c2e0368f0bc4632c90334debeb359

**Comment by samuelfrnk** [comment]
TESTED with [commit](https://github.com/sopra-fs24-group-38/sopra-fs24-group-38-server/commit/1a78e8923d9baaf9ce4e22247280f7ba94f519a3)
