### ISSUE TITLE
The backend checks that rarely ever the same Words appear in all modes. 

### ISSUE THREAD

**Issue by samuelfrnk** [sopra-fs24-group-38/sopra-fs24-group-38-server#210]
Especially fpr definitions it i ^s the case that each round there are words which reappear.

**Comment by Elyisha** [comment]
eventually implemented with this commit: https://github.com/sopra-fs24-group-38/sopra-fs24-group-38-server/commit/5fc71d740e3a3e401fffd66c50feb889140e3fa0
