### ISSUE TITLE
There shouldnt be any problems parsing the AI Player's definitions

### ISSUE THREAD

**Issue by Elyisha** [sopra-fs24-group-38/sopra-fs24-group-38-server#248]

**Comment by samuelfrnk** [comment]
While trying to parse AI players definition occasionally this happens due to non-uniqueness of key definition : 
<img width="1190" alt="image" src="https://github.com/sopra-fs24-group-38/sopra-fs24-group-38-server/assets/93734771/d9e1438e-76a8-4c2b-9785-ebcf2046bdb8">

**Comment by samuelfrnk** [comment]
Server : 
<img width="561" alt="image" src="https://github.com/sopra-fs24-group-38/sopra-fs24-group-38-server/assets/93734771/dab1d018-5a7d-4558-9757-42921a74c0a9">

**Comment by samuelfrnk** [comment]
<img width="1117" alt="image" src="https://github.com/sopra-fs24-group-38/sopra-fs24-group-38-server/assets/93734771/b3b0eca9-1bfb-4d07-b689-fdcf516e96cb">

<img width="532" alt="image" src="https://github.com/sopra-fs24-group-38/sopra-fs24-group-38-server/assets/93734771/35a3f55d-f09c-45f9-83d1-57ce83b8a8f7">

fallback worked

**Comment by samuelfrnk** [comment]
commit [4036644](https://github.com/sopra-fs24-group-38/sopra-fs24-group-38-server/commit/40366441af0ec99485a5383a892461850ef9f6ff) was pushed by mistake on the [branch](https://github.com/sopra-fs24-group-38/sopra-fs24-group-38-server/tree/248-there-shouldnt-be-any-problems-parsing-the-ai-players-definitions) related to this issue. This is why I reverted the changes on the [branch](https://github.com/sopra-fs24-group-38/sopra-fs24-group-38-server/tree/248-there-shouldnt-be-any-problems-parsing-the-ai-players-definitions) with commit, pushed it onto the [proper branch  ](https://github.com/sopra-fs24-group-38/sopra-fs24-group-38-server/tree/252-the-names-of-ai-players-should-not-hinder-the-applications-scalability) and manually linked. Therefore [4036644](https://github.com/sopra-fs24-group-38/sopra-fs24-group-38-server/commit/40366441af0ec99485a5383a892461850ef9f6ff) and

**Comment by samuelfrnk** [comment]
[65383a4](https://github.com/sopra-fs24-group-38/sopra-fs24-group-38-server/commit/65383a44c4266c7971343f3608e7e508c9c7915b) split up logic to inhance single responsibility on method level

**Comment by samuelfrnk** [comment]
Purposefully break the parsing in 50 % of the case to test fallback logic worked: 

![image](https://github.com/sopra-fs24-group-38/sopra-fs24-group-38-server/assets/93734771/3d77799c-17c1-4ceb-a03c-44c8b533d52f)

One definition was fetched from the fallback json 
![image](https://github.com/sopra-fs24-group-38/sopra-fs24-group-38-server/assets/93734771/59cc8b2f-3070-4108-9729-ad1e963dc7e6)

And one was used from gpt request : 
![image](https://github.com/sopra-fs24-group-38/sopra-fs24-group-38-server/assets/93734771/d11056a3-8a3e-4d88-952e-d8455ca8f5a9)

**Comment by samuelfrnk** [comment]
![image](https://github.com/sopra-fs24-group-38/sopra-fs24-group-38-server/assets/93734771/fe2cc775-713c-4670-a0a1-9b861136cfe8)

Also the case where chatGPT doesnt provide a proper jsonArray is covered and the game is playable

**Comment by samuelfrnk** [comment]
tested with commit e585a27b2e5ec48883ec2a770760489ca58966a7
