### ISSUE TITLE
The backend can change to state of a lobby according to which mode is played

### ISSUE THREAD

**Issue by Elyisha** [sopra-fs24-group-38/sopra-fs24-group-38-server#65]

**Comment by samuelfrnk** [comment]
closed with [commit](https://github.com/sopra-fs24-group-38/sopra-fs24-group-38-server/issues/44)

**Comment by samuelfrnk** [comment]
tested with [commit](https://github.com/sopra-fs24-group-38/sopra-fs24-group-38-server/commit/451ec42b37b495c1dbc3644e8ab1fd2c6398f11c)
