### ISSUE TITLE
The backend evaluates how many points each player scored with their vote

### ISSUE THREAD

**Issue by Elyisha** [sopra-fs24-group-38/sopra-fs24-group-38-server#81]

**Comment by Elyisha** [comment]
51114b9b7c5c2e0368f0bc4632c90334debeb359

**Comment by samuelfrnk** [comment]
# Closed with commits 

- e4fc5bd (Vote register endpoint design)
- 51114b9 (Vote register logic)  
- c647a38 (Evaluation logic) 
- 6c8ab68 (Specification allignements) 
- 46fec6f (evaluation enum added)
