### ISSUE TITLE
The backend notices the frontend as soon as all the votes are cast

### ISSUE THREAD

**Issue by Elyisha** [sopra-fs24-group-38/sopra-fs24-group-38-server#82]

**Comment by samuelfrnk** [comment]
Done with [commit](https://github.com/sopra-fs24-group-38/sopra-fs24-group-38-server/commit/51114b9b7c5c2e0368f0bc4632c90334debeb359)

**Comment by samuelfrnk** [comment]
# Closed With commit 

https://github.com/sopra-fs24-group-38/sopra-fs24-group-38-server/commit/51114b9b7c5c2e0368f0bc4632c90334debeb359 (Notification 'votes_finished) 'via websockets if all votes are received 
![image](https://github.com/sopra-fs24-group-38/sopra-fs24-group-38-server/assets/93734771/18aeddaf-2569-42ed-8c2c-03f4f51ece5b)
