### ISSUE TITLE
The backend tells the frontend how many points the player scored in the round as well as the points of the other players and who he has been fooled by (if he has been fooled)

### ISSUE THREAD

**Issue by Elyisha** [sopra-fs24-group-38/sopra-fs24-group-38-server#87]

**Comment by Elyisha** [comment]
da4c2e0201026837af9e35cb6373606e207617c8

**Comment by samuelfrnk** [comment]
Done with 51114b9b7c5c2e0368f0bc4632c90334debeb359

**Comment by samuelfrnk** [comment]
TESTED with [commit](https://github.com/sopra-fs24-group-38/sopra-fs24-group-38-server/commit/1a78e8923d9baaf9ce4e22247280f7ba94f519a3)
